services:
  postgres:
    container_name: postgres
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  airflow-webserver:
    container_name: airflow-webserver
    image: apache/airflow:2.8.1
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE_NAME}
      AIRFLOW_CONN_POSTGRES_DB_PRODUCTS_ETL: postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE_NAME}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${SECRET_KEY}
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW_VAR_WEBSITE_PATH: ${WEBSITE_PATH}
      AIRFLOW_VAR_CATEGORY: ${CATEGORY}
      PYTHONPATH: /opt/airflow
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data/raw:/opt/airflow/data/raw
      - ./data/transformed:/opt/airflow/data/transformed
      - ./etl:/opt/airflow/etl
      - ./sql/create:/opt/airflow/sql/create
      - ./sql/insert:/opt/airflow/sql/insert
      - ./utils:/opt/airflow/utils
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create --username ${AIRFLOW_WWW_USER_USERNAME} --password ${AIRFLOW_WWW_USER_PASSWORD} --firstname admin --lastname admin --role Admin --email test@gmail.com &&
      airflow webserver
      "

  airflow-scheduler:
    container_name: airflow-scheduler
    image: apache/airflow:2.8.1
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE_NAME}
      AIRFLOW_CONN_POSTGRES_DB_PRODUCTS_ETL: postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE_NAME}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${SECRET_KEY}
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW_VAR_WEBSITE_PATH: ${WEBSITE_PATH}
      AIRFLOW_VAR_CATEGORY: ${CATEGORY}
      PYTHONPATH: /opt/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data/raw:/opt/airflow/data/raw
      - ./data/transformed:/opt/airflow/data/transformed
      - ./etl:/opt/airflow/etl
      - ./sql/create:/opt/airflow/sql/create
      - ./sql/insert:/opt/airflow/sql/insert
      - ./utils:/opt/airflow/utils
    command: airflow scheduler

  airflow-init:
    container_name: airflow-init
    image: apache/airflow:2.8.1
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE_NAME}
      AIRFLOW_CONN_POSTGRES_DB_ETL: postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE_NAME}
      AIRFLOW_VAR_WEBSITE_PATH: ${WEBSITE_PATH}
      AIRFLOW_VAR_CATEGORY: ${CATEGORY}
    command:  >
      bash -c "
      airflow db migrate &&
      airflow connections add postgres_db_etl --conn-uri postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE_NAME} &&
      airflow users list | grep admin || \
      airflow users create --username ${AIRFLOW_WWW_USER_USERNAME} --password ${AIRFLOW_WWW_USER_PASSWORD} --firstname admin --lastname admin --role Admin --email test@gmail.com
      "
    restart: "no"

volumes:
  postgres_data:
